import type { Metadata } from "next";
import "./globals.css";
import CustomWagmiProvider from "@/provider/WagmiProvider";
import SessionProvider from "../provider/AuthProvider";
import { getServerSession } from "next-auth";
import { connectToDatabase } from "@/lib/mongodb";

export const metadata: Metadata = {
  title: "Goblin",
  description: "Generated by Turbold",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  await connectToDatabase(); // Establish connection on server startup
  return (
    <html lang="en">
      <body className="antialiased">
        <CustomWagmiProvider>
          <SessionProvider session={session}>{children}</SessionProvider>
        </CustomWagmiProvider>
      </body>
    </html>
  );
}
